import { useSession } from "next-auth/react";
import type { NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useRouter } from 'next/router';

const SinglePostPage: NextPage = () => {
  const { data : session,  } = useSession();
  const user = session?.user;
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="flex flex-col items-center">
          <div>Profile View</div>
          {user && <div>{`${user.name}`}</div>}
          <button onClick={() => router.back()}>Go back</button>
        </div>
      </main>
    </>
  );
}

export default SinglePostPage;